name: 🚲Publish NPM Package

# Controls when the action will run.
on:
    # Triggers the workflow on push or pull request events but only for the master branch
    push:
        tags:
            - 'v*'

    workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: pnpm/action-setup@v2
              with:
                version: latest

            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org/
                  cache: 'pnpm'

            - name: 🚓loading denpendencies
              run: pnpm i --frozen-lockfile

            - name: 🚕build library
              run: pnpm build

            - name: 🚚pnpm publish package
              run: pnpm publish --no-git-checks
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
